version: "3.8"
services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 5000:5000

  mysql:
    container_name: mysql
    platform: linux/amd64
    restart: always
    image: mysql:8.0
    ports: 
      - 3309:3306
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Admin@123
      MYSQL_DATABASE: 'demo'

volumes:
  mysql-data:
